# 4장

<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/rickiepark/math4ds/blob/main/ch4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

예제 4-1

In [1]:
v = [3, 2]
print(v)

[3, 2]


예제 4-2

In [2]:
import numpy as np
v = np.array([3, 2])
print(v)

[3 2]


예제 4-3

In [3]:
import numpy as np
v = np.array([4, 1, 2])
print(v)

[4 1 2]


예제 4-4

In [4]:
import numpy as np
v = np.array([6, 1, 5, 8, 3])
print(v)

[6 1 5 8 3]


예제 4-5

In [5]:
from numpy import array

v = array([3,2])
w = array([2,-1])

# 벡터 더하기
v_plus_w = v + w

# 더해진 벡터 출력하기
print(v_plus_w)

[5 1]


예제 4-6

In [6]:
from numpy import array

v = array([3,1])

# 벡터 스케일링
scaled_v = 2.0 * v

# 스케일링된 벡터 출력
print(scaled_v)

[6. 2.]


예제 4-7

In [7]:
from numpy import array

# i-hat과 j-hat으로 구성된 기저 행렬을 만듭니다
basis = array(
    [[3, 0],
     [0, 2]]
 )

# 벡터 v를 정의합니다
v = array([1,1])

# 점곱으로 v에 변환을 적용하여 새로운 벡터를 만듭니다
new_v = basis.dot(v)

print(new_v)

[3 2]


예제 4-8

In [8]:
from numpy import array

# i-hat과 j-hat을 선언합니다
i_hat = array([2, 0])
j_hat = array([0, 3])

# i-hat과 j-hat을 사용해 기저 행렬을 만들고
# 열과 행을 바꿔야 합니다
basis = array([i_hat, j_hat]).transpose()

# 벡터 v를 선언합니다
v = array([1,1])

# 점곱으로 v에 변환을 적용하여 새로운 벡터를 만듭니다
new_v = basis.dot(v)

print(new_v) # [2, 3]

[2 3]


예제 4-9

In [9]:
from numpy import array

# i-hat과 j-hat을 선언합니다
i_hat = array([2, 0])
j_hat = array([0, 3])

# i-hat과 j-hat을 사용해 기저 행렬을 만들고
# 열과 행을 바꿔야 합니다
basis = array([i_hat, j_hat]).transpose()


# 벡터 v를 선언합니다
v = array([2,1])

# 점곱으로 v에 변환을 적용하여 새로운 벡터를 만듭니다
new_v = basis.dot(v)

print(new_v)

[4 3]


예제 4-10

In [10]:
from numpy import array

# i-hat과 j-hat을 선언합니다
i_hat = array([2, 3])
j_hat = array([2, -1])

# i-hat과 j-hat을 사용해 기저 행렬을 만들고
# 열과 행을 바꿔야 합니다
basis = array([i_hat, j_hat]).transpose()

# 벡터 v를 선언합니다
v = array([2,1])

# 점곱으로 v에 변환을 적용하여 새로운 벡터를 만듭니다
new_v = basis.dot(v)

print(new_v)

[6 5]


예제 4-11

In [11]:
from numpy import array

# 변환 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# 변환 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# 변환 통합
combined = transform2 @ transform1

# 테스트
print("통합 행렬:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))

통합 행렬:
 [[ 1 -1]
 [ 1  0]]
[-1  1]


예제 4-12

In [12]:
from numpy import array

# 변환 1
i_hat1 = array([0, 1])
j_hat1 = array([-1, 0])
transform1 = array([i_hat1, j_hat1]).transpose()

# 변환 2
i_hat2 = array([1, 0])
j_hat2 = array([1, 1])
transform2 = array([i_hat2, j_hat2]).transpose()

# 변환 통합, 전단을 먼저 적용하고 그다음 회전을 적용합니다
combined = transform1 @ transform2

# 테스트
print("통합 행렬:\n {}".format(combined))

v = array([1, 2])
print(combined.dot(v))

통합 행렬:
 [[ 0 -1]
 [ 1  1]]
[-2  3]


예제 4-13

In [13]:
from numpy.linalg import det
from numpy import array

i_hat = array([3, 0])
j_hat = array([0, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

6.0


예제 4-14

In [14]:
from numpy.linalg import det
from numpy import array

i_hat = array([1, 0])
j_hat = array([1, 1])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

1.0


예제 4-15

In [15]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([1, 2])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

-5.000000000000001


예제 4-16

In [16]:
from numpy.linalg import det
from numpy import array

i_hat = array([-2, 1])
j_hat = array([3, -1.5])

basis = array([i_hat, j_hat]).transpose()

determinant = det(basis)

print(determinant)

0.0


예제 4-17

In [17]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

# A와 그 역행렬의 점곱은 항등 행렬을 만듭니다
inverse = A.inv()
identity = inverse * A

# Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
print("역행렬: {}".format(inverse))

# Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
print("항등 행렬: {}".format(identity))

역행렬: Matrix([[-1/2, 0, 1/3], [11/2, -2, -4/3], [-2, 1, 1/3]])
항등 행렬: Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])


예제 4-18

In [18]:
from numpy import array
from numpy.linalg import inv

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = array([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = array([
    44,
    56,
    72
])

X = inv(A).dot(B)

print(X)

[ 2. 34. -8.]


예제 4-19

In [19]:
from sympy import *

# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72

A = Matrix([
    [4, 2, 4],
    [5, 3, 7],
    [9, 3, 6]
])

B = Matrix([
    44,
    56,
    72
])

X = A.inv() * B

print(X)

Matrix([[2], [34], [-8]])


예제 4-20

In [20]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("고윳값")
print(eigenvals)
print("\n고유 벡터")
print(eigenvecs)

고윳값
[-0.46410162  6.46410162]

고유 벡터
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


예제 4-21

In [21]:
from numpy import array, diag
from numpy.linalg import eig, inv

A = array([
    [1, 2],
    [4, 5]
])

eigenvals, eigenvecs = eig(A)

print("고윳값")
print(eigenvals)
print("\n고유 벡터")
print(eigenvecs)

print("\n재구성 행렬")
Q = eigenvecs
R = inv(Q)

L = diag(eigenvals)
B = Q @ L @ R

print(B)

고윳값
[-0.46410162  6.46410162]

고유 벡터
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]

재구성 행렬
[[1. 2.]
 [4. 5.]]
